### PR TITLE
Enable HMRC webchat for specialist tax trusts

### PR DESCRIPTION
**Pull request by tvararu**
This should go out on the 15th of December.

Trello card: https://trello.com/c/dtueOo2D/530-click-to-chat

### CODE REVIEW

**Comment by sihugh** [comment]
Seems in line with what's gone before.  Where does the queue ID come from?

**Comment by tvararu** [comment]
@sihugh It's a hardcoded identifier they provide us, each page potentially has a different one. The trello card has a link to a google spreadsheet with them.

**Comment by sihugh** [comment]
Cool, merge when ready 👍

**Comment by tvararu** [comment]
Cheers @sihugh! 🙌

**Pull request merged**
