### PR TITLE
Add jenkins-schema.sh to verify contacts-frontend against the schemas

### PR DESCRIPTION
**Pull request by issyl0**
As noted in https://github.com/alphagov/contacts-frontend/pull/37#issuecomment-163666678. Copied from `contacts-admin`, with some words changed to refer to `contacts-frontend`.

### CODE REVIEW

**Comment by boffbowsh** [comment]
Something needs to call this script too

**Comment by issyl0** [comment]
@boffbowsh We've just made the `govuk_contacts_frontend_schema_tests` job in CI and added it to the triggers on the main content_schemas master and branches jobs.

**Comment by boffbowsh** [comment]
I've just tested whether the new job gets run on CI, and it doesn't seem to at the moment.

**Comment by boffbowsh** [comment]
Ah, I am mistaken.

**Comment by tijmenb** [comment]
@issyl0 @boffbowsh I think the jenkins script is failing:

https://ci.dev.publishing.service.gov.uk/job/govuk_contacts_frontend_schema_tests/4/console

FWIW, in collections-publisher the jenkins-schema.sh calls the normal jenkins.sh to run the tests:

https://github.com/alphagov/collections-publisher/blob/master/jenkins-schema.sh

Might be useful here too.

**Comment by issyl0** [comment]
Interesting, thanks for bringing this up, @tijmenb. I thought Jenkins would email me about failures. I'll look into it on Monday.

**Pull request merged**
