### PR TITLE
Set slimmer template to be wrapper

### PR DESCRIPTION
**Pull request by edds**
Explicitly set the slimmer template to be wrapper so that it isn't
effected by changes to the default when slimmer is updated.

### CODE REVIEW

**Comment by jamiecobbett** [comment]
I think this app is due to be decommissioned and moved to gds-attic - @jennyd?

**Comment by edds** [comment]
But it still serves this page? https://www.gov.uk/government/organisations/hm-revenue-customs/contact/alcohol-duties-national-registration-unit

**Comment by bradleywright** [comment]
@jamiecobbett I believe you're thinking of https://github.com/alphagov/contacts-admin

**Comment by jamiecobbett** [comment]
Oops, brain fart. I was thinking of https://github.com/alphagov/courts-frontend

**Pull request merged**
